language: python

sudo: false

python:
  - 3.6
    # - "3.7-dev"  # waiting on sphinx-autodoc-typehints GenericMeta fix

addons:
  apt:
    packages:
      - graphviz

before_install:
  - pip install -U pip
  - pip install coveralls coverage mypy

install:
  - pip install -e .[development]

script:
  - coverage run -a `which py.test` -vv
  - make -C docs/ html
  - mypy uqbar

after_success:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
