language: python

sudo: false

python:
  - 3.6
    # - "3.7-dev"  # waiting on sphinx-autodoc-typehints GenericMeta fix

addons:
  apt:
    packages:
      - graphviz

before_install:
  - pip install -U pip
  - pip install black coveralls mypy

install:
  - pip install -e .[development]

script:
  - make black-check
  - make flake8
  - make mypy
  - make pytest
  - make docs

after_success:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
