language: python
dist: xenial
sudo: false

python:
- "3.6"
- "3.7"
- "3.8-dev"

addons:
  apt:
    packages:
    - graphviz

before_install:
- pip install -U pip

install:
- pip install -e .[test]

script:
- make black-check
- make flake8
- make mypy
- make pytest
- make docs

after_success:
- coveralls

notifications:
  email:
    on_success: never
    on_failure: always
